version: '3.9'
networks:
  local-network:
    driver: bridge
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=migr
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis-master:
    image: 'bitnami/redis:latest'
    network_mode: "host"
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=ReDiS777
    volumes:
      - redis:/bitnami

  redis-replica:
    image: 'bitnami/redis:latest'
    network_mode: "host"
    ports:
      - '6378:6378'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=ReDiS777
      - REDIS_PASSWORD=ReDiS777
  migration:
    image: 'migrate/migrate'
    network_mode: "host"
    depends_on:
      - db
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable", "up", "2" ]
    volumes:
      - './database/migrations:/migrations'
  service:
    image: go-server:latest
    restart: always
    network_mode: "host"
    environment:
      - DATABASE_URL=localhost:5432
    ports:
      - '8080:8080'
volumes:
  db:
    driver: local
  redis:
    driver: local