database:
  addr: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  database: "postgres"
server:
  url: "localhost:8080"
redis:
  addr: "localhost"
  port: "6379"
  password: "ReDiS777"